#!/bin/sh

if [ -n "$DISPLAY" ]; then
	if which xfte >/dev/null; then
		exec xfte "$@"
	elif which sfte >/dev/null; then
		exec sfte "$@"
	else
		echo "Only Console version installed"
	fi
else
	if [ "$TERM"=linux ] && which vfte >/dev/null; then
		exec vfte "$@"
	elif which sfte >/dev/null; then
		exec sfte "$@"
	else
		echo "Only X-Window version installed"
	fi
fi
